// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGn-bzD15kLFiNzhFxoxGE8aDFUfGCprY',
    appId: '1:77905712753:web:a80325912e4703d747add0',
    messagingSenderId: '77905712753',
    projectId: 'amikom-dss',
    authDomain: 'amikom-dss.firebaseapp.com',
    databaseURL: 'https://amikom-dss-default-rtdb.firebaseio.com',
    storageBucket: 'amikom-dss.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDppPDMFfJVzbYaspkPADlG_tWaGurynEY',
    appId: '1:77905712753:android:24ce38bf326fa68447add0',
    messagingSenderId: '77905712753',
    projectId: 'amikom-dss',
    databaseURL: 'https://amikom-dss-default-rtdb.firebaseio.com',
    storageBucket: 'amikom-dss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB905vO3BM3mNmciY9u7609aDMLUSye_QU',
    appId: '1:77905712753:ios:595f1fff3db2be7f47add0',
    messagingSenderId: '77905712753',
    projectId: 'amikom-dss',
    databaseURL: 'https://amikom-dss-default-rtdb.firebaseio.com',
    storageBucket: 'amikom-dss.appspot.com',
    androidClientId: '77905712753-jjnsktnuq5subuf35vk8ai590dthpnvc.apps.googleusercontent.com',
    iosClientId: '77905712753-vlj8lobk4g29h78chfdja08rjh5p82dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.otoranger',
  );
}
